name: BuilderHelper
author: XdmingXD
main: BuilderHelper\builderhelper
version: 1.0.3
api: [2.0.0 , 3.0.0-ALPHA4 , 3.0.0-ALPHA5]

commands: 
  bh:
    description: "Show the help list of builderhelper"
    permission: "yolo.command.bh"
    usage: "/bh"
  bh pos:
    description: "Show your current position"
    permission: "yolo.command.pos"
    usage: "/bh pos"
  bh start:
    description: "Start to count how many blocks you want to place"
    permission: "yolo.command.start"
    usage: "/bh start <counts>"
  bh placed:
    description: "show your current position"
    permission: "yolo.command.pos"
    usage: "/bh pos"
permission:
    yolo.command.placed:
        default: true
        description: "Show the help list of builderhelper"
    yolo.command.pos:
        default: true
        description: "Show your current position"
    yolo.command.start:
        default: true
        description: "Start to count how many blocks you want to place"
    yolo.command.placed:
        default: true
        description: "show your current position"
---
